name:                c-mlir
version:             0.1.0.0
github:              "wehu/c-mlir"
license:             BSD3
author:              "wei.hu"
maintainer:          "wei.hu@enflame-tech.com"
copyright:           "2021 Wei Hu"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/c-mlir#readme>

dependencies:
- base >= 4.7 && < 5
- mlir-hs
- language-c
- utf8-string
- containers
- mtl
- transformers
- lens
- array
- vector
- optparse-applicative

library:
  source-dirs: src

executables:
  c-mlir-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - c-mlir

tests:
  c-mlir-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - c-mlir
    - hspec
    - raw-strings-qq
    - bytestring
    - QuickCheck
